name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-bionic

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Install Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Build the Docker Image
      run: | 
       docker buildx build \
       --file Dockerfile \
       --tag at-notifiers:latest \
       -- platform linux/amd64, linux/arm/v7, linux/arm64 . 
